### ISSUE TITLE
Error when specifying the version.

### ISSUE THREAD

**Issue by phillipsj** [agc93/ClickTwice#1]
I receive the error below when specifying a version.  It seems MSBuild expect it to have the following format: 1.44.2.%2a, with the %2A being the revision.

Command:

       PublishApp(project)  
        .WithHandler(new AppInfoHandler(new AppInfoManager()))
				.WithHandler(new AppDetailsPageHandler("ClickTwice.Templates.SolidState") {
					FileNameMap = new Dictionary<string, string> {
						{"index.html", "details.html"}
					}
				})
				.WithHandler(new InstallPageHandler(fileName: "index.html", linkText: "Details",   linkTarget: "details.html"))
        .SetConfiguration(configuration)
        .ForceRebuild()
        .ThrowOnHandlerFailure()
        .WithVersion(buildVersion.Version) 
        .To("./artifacts/publish/");

Error:

    error MSB3174: Invalid value for 'AssemblyVersion'.

**Comment by phillipsj** [comment]
So it seems if I do the following:  

    .WithVersion($"{buildVersion.Version}.%2a")

It works perfectly fine as it expects the %2a to be included.  Is this something you thing should be handled automatically?  If so I can submit a PR, just let me know.

**Comment by agc93** [comment]
I'll look into this as yeah this probably does seem to be something it should handle (or at least be documented).

Thanks heaps @phillipsj !

**Comment by agc93** [comment]
@phillipsj Prerelease version `0.2.0-unstable0001` available on NuGet now with fix for this. Try it out, and if it works for you, I'll release a stable 0.1.2 package.

**Comment by phillipsj** [comment]
I am still getting the following error, I am using MSBuild 15 (VS 2017) if that helps.  

    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(3680,5): error MSB3174: Invalid value for 'AssemblyVersion'.

With the following as an input

    .WithVersion("1.45.0")

If I include the %2a then it works fine.

**Comment by Lakritzator** [comment]
Can it be some weird encoding thing? %2A is the "URL" encoded value of "*"

**Comment by Lakritzator** [comment]
According to MSDN documentation, the AssemblyVersion is supposed to have 4 parts. Your example has only 3 (1.45.0), so this gives an error. A "*" is accepted, and says to take a default (whatever that is)
Read more here:
https://msdn.microsoft.com/en-us/library/system.reflection.assemblyversionattribute.aspx

So I think your problem is solved when you add a 4th part to your version, and the error is not directly in the ClickTwice implementation.

P.S.
I didn't test this, I just stumbled upon this while evaluating this project.

**Comment by agc93** [comment]
@phillipsj @Lakritzator I've published another prerelease: [`unstable0002`](https://www.nuget.org/packages/Cake.ClickTwice/0.2.0-unstable0002) that *should* fix it this time.

I'll leave this open until you can confirm it's working now!

---

Looks like it was just a dodgy padding mistake so I've added a test that should pick this up in future :smile:
